import type { Machinery, Reservation } from "./types"

export const MOCK_MACHINERY: Machinery[] = [
  {
    id: "1",
    title: "Tractor John Deere 5075E",
    description: "Tractor en excelente estado, 75 HP, con aire acondicionado y transmisión hidrostática",
    type: "tractor",
    condition: "excelente",
    transactionType: "venta",
    price: 450000,
    location: "Jalisco, México",
    imageUrl: "/john-deere-tractor.jpg",
    ownerId: "2",
    ownerName: "John Farmer",
    status: "aprobada",
    createdAt: new Date("2025-01-15"),
    brand: "John Deere",
    model: "5075E",
    year: 2022,
  },
  {
    id: "2",
    title: "Cosechadora Case IH Axial-Flow",
    description: "Cosechadora de granos con sistema de limpieza avanzado, ideal para maíz y soya",
    type: "cosechadora",
    condition: "bueno",
    transactionType: "renta",
    price: 15000,
    location: "Sinaloa, México",
    imageUrl: "/combine-harvester-field.png",
    ownerId: "2",
    ownerName: "John Farmer",
    status: "aprobada",
    createdAt: new Date("2025-01-10"),
    brand: "Case IH",
    model: "Axial-Flow 250",
    year: 2020,
  },
  {
    id: "3",
    title: "Sembradora de Precisión Massey Ferguson",
    description: "Sembradora de 12 surcos con sistema de dosificación neumática",
    type: "sembradora",
    condition: "nuevo",
    transactionType: "venta",
    price: 280000,
    location: "Guanajuato, México",
    imageUrl: "/seed-planter-agricultural.jpg",
    ownerId: "2",
    ownerName: "John Farmer",
    status: "aprobada",
    createdAt: new Date("2025-01-12"),
    brand: "Massey Ferguson",
    model: "MF 400",
    year: 2024,
  },
  {
    id: "4",
    title: "Pulverizador Autopropulsado",
    description: "Pulverizador con barra de 24 metros, tanque de 3000 litros",
    type: "pulverizador",
    condition: "usado",
    transactionType: "renta",
    price: 8000,
    location: "Sonora, México",
    imageUrl: "/agricultural-sprayer.png",
    ownerId: "2",
    ownerName: "John Farmer",
    status: "aprobada",
    createdAt: new Date("2025-01-08"),
    brand: "Jacto",
    model: "Uniport 3000",
    year: 2019,
  },
  {
    id: "5",
    title: "Tractor New Holland T6.180",
    description: "Tractor de 180 HP con cabina de lujo y GPS integrado",
    type: "tractor",
    condition: "excelente",
    transactionType: "venta",
    price: 680000,
    location: "Michoacán, México",
    imageUrl: "/new-holland-tractor.jpg",
    ownerId: "2",
    ownerName: "John Farmer",
    status: "pendiente",
    createdAt: new Date("2025-01-16"),
    brand: "New Holland",
    model: "T6.180",
    year: 2023,
  },
  {
    id: "6",
    title: "Rastra de Discos 32 Platos",
    description: "Rastra pesada para preparación de suelo, 32 discos de 26 pulgadas",
    type: "otro",
    condition: "bueno",
    transactionType: "venta",
    price: 95000,
    location: "Veracruz, México",
    imageUrl: "/disc-harrow-agricultural.jpg",
    ownerId: "2",
    ownerName: "John Farmer",
    status: "aprobada",
    createdAt: new Date("2025-01-05"),
    year: 2021,
  },
]

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: "1",
    machineryId: "2",
    machineryTitle: "Cosechadora Case IH Axial-Flow",
    userId: "2",
    userName: "John Farmer",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-15"),
    totalPrice: 210000,
    status: "confirmada",
    createdAt: new Date("2025-01-18"),
  },
  {
    id: "2",
    machineryId: "4",
    machineryTitle: "Pulverizador Autopropulsado",
    userId: "2",
    userName: "John Farmer",
    startDate: new Date("2025-01-25"),
    endDate: new Date("2025-01-30"),
    totalPrice: 40000,
    status: "pendiente",
    createdAt: new Date("2025-01-20"),
  },
]
